---
daemon:
  modules:
    - Xim
    - Wayland
    - Indicator
indicator:
  icon_color: Black
log:
  global_level: DEBUG
engine:
  default_category: Latin
  global_category_state: false
  global_hotkeys:
    M-C-Backslash:
      behavior: !Mode Math
      result: ConsumeIfProcessed
    S-Space:
      behavior: !Toggle
        - Hangul
        - Latin
      result: Consume
    Hangul:
      behavior: !Toggle
        - Hangul
        - Latin
      result: Consume
    C-S-Space:
      behavior: !Mode Emoji
      result: ConsumeIfProcessed
    Esc:
      behavior: !Switch Latin
      result: Bypass
  category_hotkeys:
    Hangul:
      ControlR:
        behavior: !Mode Hanja
        result: Consume
      HangulHanja:
        behavior: !Mode Hanja
        result: Consume
      F9:
        behavior: !Mode Hanja
        result: ConsumeIfProcessed
  mode_hotkeys:
    Math:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Hanja:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Emoji:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
  xim_preedit_font:
    - D2Coding
    - 15.0
  latin:
    layout: Colemak
    preferred_direct: true
  hangul:
    layout: dubeolsik
    word_commit: false
    preedit_johab: Needed
    addons:
      dubeolsik:
        - TreatJongseongAsChoseong
